# Generated by Django 3.2.4 on 2021-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0005_auto_20210721_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
