# Generated by Django 3.2.4 on 2021-07-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0010_alter_post_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
